multiples(1000);
fibonacci(4000000);
largestPrime(600851475143);

function addToPage(message, result){
	var resultDIV = '<li class="result">MESSAGE : <b>RESULT</b></li>';
	resultDIV = resultDIV.replace("MESSAGE", message);
	resultDIV = resultDIV.replace("RESULT", result);
	$("#answers").append(resultDIV);
}

function multiples(value) {
	/*If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
	Find the sum of all the multiples of 3 or 5 below 1000.*/

	var result = 0; for(i=0;i<value;i++){     
		if (i%5===0 || i%3===0) result += i;
	}
	addToPage('Multiples of 3 or 5 below 1000', result);
}

function fibonacci(maximumValue){
	/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

	var a = 1;
	var b = 2;
	var sum = 0;
	while(b<maximumValue) {
		var c = a+b;
		a=b;
		b=c;
		if (a%2 === 0) sum += a;
	}
	addToPage("Find the sum of the even-valued terms below 40000000",sum);
}

function largestPrime(number){
	/*The prime factors of 13195 are 5, 7, 13 and 29.
	What is the largest prime factor of the number 600851475143 ?*/
	var result = 0;

	addToPage('Largest prime factor of 600851475143', result || 'Working on it...')
}
